name: complex workflow

on: push

jobs:
  job1:
    name: ubuntu job
    runs-on: ubuntu-latest
    steps:
      - name: ubuntu-date
        run: date
  job2:
    name: windows job
    needs: job1
    runs-on: windows-latest
    steps:
      - name: windows-date
        run: Get-Date
  job3:
    name: macos job
    needs: [job1, job2]
    runs-on: macos-latest
    steps:
      - name: macos-date
        run: date
  job4:
    name: macos-11 job
    needs: [job1, job2, job3]
    runs-on: macos-11
    steps:
      - name: macos-11-date
        run: date

